### ISSUE TITLE
[Feat] 카테고리

### ISSUE THREAD

**Issue by leobang17** [leobang17/gatsby-theme-simplex#10]
## 💡 어떤 기능을 구현하나요?

node 생성시 카테고리 생성 및 카테고리바 좌측 출력
카테고리 페이지 생성

## 📝 todo
- [ ] onCreateNode -> 카테고리 생성
- [ ] 카테고리 dynamic page 생성 (createPage? FileSystemRoute API?)
- [ ] 카테고리 좌측 출력.
