### ISSUE TITLE
[Feat] Layout 수정 및 Footer 생성

### ISSUE THREAD

**Issue by leobang17** [leobang17/gatsby-theme-simplex#20]
## 💡 어떤 기능을 구현하나요?

반응형에 맞게 Layout 수정

## 📝 todo

- [x] 반응형에 맞게 Layout 수정
  - [x] bp 3개 (mobile - laptop -desktop) 
- [x] CategoryPage도 전용 Layout 생성
  - [x] LeftStack 역시 상속한 Layout이 주입하도록 변경
- [x] Footer 만들기
- [x] 페이지 min-height 조절 (footer는 항상 바닥에 붙어있도록)

[Feat] Footer 생성 및 page의 min-height 조정 (#20)
- Footer의 값은 config.ts의 값 재탕.
- body의 default margin 값 삭제
- flex와 min-height을 이용해 footer는 항상 바닥에 존재함
  - 페이지의 내용이 부족할 때는 HStack의 height을 확장.
