### ISSUE TITLE
[Feat] 카테고리 사이드바 개선

### ISSUE THREAD

**Issue by leobang17** [leobang17/gatsby-theme-simplex#21]
## 💡 어떤 기능을 구현하나요?

Category 사이드바를 개선합니다. 
- slug
- 카테고리 data fetching 방식
- 전체적인 스타일링 

## 📝 todo

- [x] Category Page 혹은 Article Page에서 현재 속한 카테고리 볼드 처리
- [x] 카테고리 슬러그 수정
  - [x] slugify -> lowercase로 변경. 
    - 현재 슬러그가 category title로 사이드바에 그대로 출력되고 있음
  - [x] 원래 title을 사이드 바에 출력
- [x] 카테고리 선택 박스 바운더리 수정 (지금은 옆에 클릭해도 인식함)
- [x] category tree는 Context API에서 가져오도록 변경
- [x] Category 사이드 바 스타일링
