### ISSUE TITLE
[Feat] ArticlePage 개선

### ISSUE THREAD

**Issue by leobang17** [leobang17/gatsby-theme-simplex#22]
## 💡 어떤 기능을 구현하나요?

Article Page을 개선합니다.

## 📝 todo

- [x] PageQuery 수정
  - [x] 불필요한 field 제거
  - [x] min read 추가 
- [x] Title 및 작성일자 재배치
- [ ] 작성자 profile
- [ ] TOC 사이드 바 수정 
  - [ ] 스크롤을 따라 중심으로 toc 사이드바도 움직이도록 변경
  - [x] useTableOfContentsObserver의 threshold 0.1으로 줄이기. (지금 감도가 좀 낮은 듯함)
  - [x] hover시 천천히 켜지게 변경
  - [x] active 시 font-size가 커지는게 아니라 왼쪽으로 밀리도록 변경
- [ ] 하단에 공백 추가 
  - 일정 이상 공백이 없으니 toc 사이드바의 항목이 observer에 포착되지 않음

**Comment by yunseonyeong** [comment]
빨리 해잉
