### ISSUE TITLE
[Feat] Footer 반응형 개선

### ISSUE THREAD

**Issue by leobang17** [leobang17/gatsby-theme-simplex#23]
## 💡 어떤 기능을 구현하나요?

Footer 반응형 개선. 현재는 모바일 화면너비에서 overflow로 밑으로 텍스트가 밀린다.

## 📝 todo
- [ ] react-response 의존성 설치
- [ ] responsive break point들에 대해 hook 생성
- [ ] Mobile 용 Footer 생성... 분기처리는 Footer 컴포넌트안에서. 

## References 
- https://www.npmjs.com/package/react-responsive
- https://velog.io/@pyo-sh/React-Responsive
