### ISSUE TITLE
[Feat] MDX content 스타일링 및 개선사항

### ISSUE THREAD

**Issue by leobang17** [leobang17/gatsby-theme-simplex#25]
## 💡 어떤 기능을 구현하나요?

MDX 스타일링이 되어있지 않은 상태입니다. 
MDXProvider를 이용해 전체적인 스타일을 적용하고, 기존 미흡한 점을 개선합니다. 

## 📝 todo
- [x] MDXProvider를 이용해 스타일링
- [x] CodeBlock 문제 해결. 
  - code block을 일단은 width에 맞게 줄어들도록 했지만, 남은 공간이 scroll로 overflow되는게 아니라 줄바꿈되어서 밑으로 감. 
  - 그래서 코드의 가독성이 떨어지는데, 모바일 환경에서 특히 이상할 듯
  - window width에 맞게 code block의 width가 줄어들고, 남은 공간이 x축으로 scroll되도록 변경해야함.
- [x] remark 이미지 적용
- [x] remark external link 적용
- [x] 수식을 위한 markdown 문법 (달러싸인)을 이용할 경우 뷰 전체가 깨지는데 무시하도록 적용
  - remark katex 라이브러리 적용하기
- [x] mdx remark 관련해서 찾아보기 .. 
  - [x] 지금 mdx의 default로 지원하는 syntax tree 작업에서 지원하지 않는 문법들이 있음.
  - [x] 특히 \``이 변환되어  \<code /> 가 되어야 하는데 \<div> 태그에 한번 더 감싸져서 나옴.
  - [x] \~~ \~~ 자체를 인식 못한다..  \<del /> tag를 꾸며줘도 소용이 없음.
- [ ] code block에 copy 버튼 달기
- [ ] code block에 title 달기
- [x] 반응형으로 font-size 줄여주기

## References
- [Mdx Remark](https://mdxjs.com/packages/remark-mdx/)
- [remark codeblock copy](https://www.gatsbyjs.com/plugins/gatsby-remark-prismjs-copy-button/?=remark%20copy)
- [remark katex](https://www.gatsbyjs.com/plugins/gatsby-remark-katex/?=katex)

**Comment by leobang17** [comment]
image box shadow 스타일링 레퍼런스
- https://getcssscan.com/css-box-shadow-examples
