### ISSUE TITLE
[Feat] Slugify 함수 개선

### ISSUE THREAD

**Issue by leobang17** [leobang17/gatsby-theme-simplex#26]
## 💡 어떤 기능을 구현하나요?

지금은  
- 소문자화
- 공백을 hyphen으로 replace
밖에 없음.

slug 전략를 보다 개선합니다. 

## 📝 todo
- [x] camel case를 인식해 hyphen으로 변경
- [x] hyphen이 중복될 경우 1개로 압축한다.
- [x] 마지막에 . 이 있을 경우 제거
