### ISSUE TITLE
[Feat] GraphQL datalayer 구조 변경 (category를 주로)

### ISSUE THREAD

**Issue by leobang17** [leobang17/gatsby-theme-simplex#27]
## 💡 어떤 기능을 구현하나요?

원래 category tree를 생성하는 노드에 대해서만 간단히 변경하려고 했는데... 그게 그렇게 간단하지 않았다.
category 관련한 구조를 뜯어고치고 이를 category tree, article page, category page에 올바르게 뿌려주도록 한다.

겸하여 dataLayer path를 생성하고 데이터레이어에 접근하는 api point를 생성한다.
기존의 산개된 함수들을 리팩토링하여 클래스화 하는게 목적인데 ... gatsby가 graphql 쿼리를  이용하는 page 와 static으로 나누어져있고, 또 이를 node api 속에서 이용할 경우 해당 api가 제공하는 parameter인 graphql 메서드를 이용해야하는지라 굳이 모든 케이스의 경우를 다루는게 필요할지는 잘 모르겠다.

## 📝 todo

- [x] CategoryPage에서 article 필터링 수정 (trailing slash 설정이 안되어있어서 다른 directory여도 그냥 startswith으로 같이 보여줌.)
- [x] Graphql data layer에 접근하는 API point 생성 
  - DataLayer (Config)
  - `API -> Service -> QueryService -> Query` 순으로 의존
- [x] Mdx.field.slug 값 변경 
  - gatsby filesystem api에서 제공하는 filepath를 그대로 썼었음
  - 이제 category directory + title 을 조합한 slug를 이용한다.
- [x] Mdx 필드에 추가한 field.category 삭제 (major, minor, slug)
  - 이제 major, minor가 아니라 하나의 string에서 파생된 CATEGORY_THRESHOLD 만큼 카테고리를 생성해서 나눈다.
- [x] raw query 한 번 싹 점검.. 필요없는 값을 가져오지 않도록
