### ISSUE TITLE
[Feat] Nav 바 개선

### ISSUE THREAD

**Issue by leobang17** [leobang17/gatsby-theme-simplex#33]
## 💡 어떤 기능을 구현하나요?

Nav 바 개선합니다.

## 📝 todo

- [x] 블로그 타이틀에 gatsby link api 연결 (index page로 가도록)
- [x] Tablet (S) 크기부터 Nav바 우 상단에 메뉴 토글 생성
- [x] 메뉴 토글의 경우 category를 수집할 수 없는 페이지일 경우 수집하지 않도록 조치
- [x] 404, 500 에러 페이지를 ErrorPageContext로 감싸줘 category context를 받을 수 있도록 변경
