### ISSUE TITLE
[Feat] CategoryPage 개선

### ISSUE THREAD

**Issue by leobang17** [leobang17/gatsby-theme-simplex#39]
## 💡 어떤 기능을 구현하나요?

CategoryPage를 개선합니다. 

## 📝 todo
- [ ] ~~어떤 카테고리에 들어온건지 맨 위에 큰 텍스트로 명시해줌.~~
- [x] CategoryPage의 전체적인 text styling
- [x] 반응형에 맞게 텍스트 크기 줄여주기
