### ISSUE TITLE
[Feat] Head API 적용, 검색 엔진 최적화

### ISSUE THREAD

**Issue by leobang17** [leobang17/gatsby-theme-simplex#45]
## 💡 어떤 기능을 구현하나요?

공식문서를 읽고 Gatsby의 Head API를 이용해 각 문서의 head tag를 채워보아요~ 

## 📝 todo

- [x] link 태그 (https://developer.mozilla.org/ko/docs/Web/HTML/Element/link)
  - 현재 문서와 외부 리소스와의 관계를 명시함 stylesheet, favicon을 설정할 때 쓰임
- [x] meta 태그
  - 다음 두 문서 참고 
    - https://developer.mozilla.org/ko/docs/Web/HTML/Element/meta#명세
    - https://developer.mozilla.org/ko/docs/Web/HTML/Element/meta/name 
  - [ ] keywords tag -> article page에 대해서 word bag 만들어서 serve 하기
- [x] ~~style 태그~~
- [x] title 태그
  - title은 최대한 descriptive 하게 작성 
- [x] base 태그 (https://developer.mozilla.org/ko/docs/Web/HTML/Element/base)
  - relative path로 탐색할 때 기준이 될 base uri를 설정.
- [x] ~~tagscript 태그~~
- [x] ~~noscript 태그~~
- [x] ~~html 태그 (얘는 property overriding)~~
- [x] ~~body 태그 (얘도 property overriding)~~
- [x] Open Graph 태그
  - [ ] twitter
  - [ ] facebook
- [x] non-sementic tag들 semantic tag로 변경하기 (nav, footer, article 등...)
- [x] ArticlePage의 uri 수정 (category를 더이상 uri endpoint에 노출하지 않도록)
- [ ] sitemap 생성 
- [ ] robots.txt 작성

## References
- [Gatsby Head API](https://www.gatsbyjs.com/docs/reference/built-in-components/gatsby-head/)
- [Gatsby SEO](https://www.gatsbyjs.com/docs/how-to/adding-common-features/adding-seo-component/)
- [Gatsby Seo Component 만들기](https://www.gatsbyjs.com/docs/tutorial/part-4/#task-use-usestaticquery-to-create-an-seo-component)
- [Seo Best Practice 10](https://www.searchenginejournal.com/important-tags-seo/156440/#close)
- [Seo 및 Open Graph 참고 블로그](https://sumini.dev/guide/010-seo-head-tag/)
- [Open Graph - naver, twitter, facebook 참고](https://velog.io/@byeol4001/Meta-Tag-OG오픈그래프-사용하기)
- [sitemap 생성 플러그인](https://www.gatsbyjs.com/plugins/gatsby-plugin-sitemap)
