### ISSUE TITLE
[Feat] 404 페이지, 500 페이지 생성

### ISSUE THREAD

**Issue by leobang17** [leobang17/gatsby-theme-simplex#46]
## 💡 어떤 기능을 구현하나요?

호스팅하고 있는 도메인 내 잘못된 route를 hit 했을 때 표시할 404 페이지를 만들어보아요

## 📝 todo
- [x] 404 404 404
- [x] image 크기 반응형으로 줄여주기
- [x] home page로 보내는 링크 달아주기
- [x] 500 internal error page 생성
