### ISSUE TITLE
[Feat] Beta (v0.0.1) 배포 준비

### ISSUE THREAD

**Issue by leobang17** [leobang17/gatsby-theme-simplex#55]
## 💡 어떤 기능을 구현하나요?

베타 버전 배포에 앞서 자잘한 작업들을 수행합니다. 

## 📝 todo
- [x] Configs.ts 수정
  - 베타버전에서는 이용되지 않는 정보까지 입력받도록 하고 있음.
  - 입력되지 않은 값은 default 값을 제공하는 하나의 layer를 더 거치도록 변경
- 유저가 설정할 수 있는 상수들 제공 
  - [x] table of content stack depth (몇번째 header까지 표시할 것인지) 
- [x] 이용하지 않는 파일들 제거 (dsg.. 등등)
- [x] repo 이름 수정... 지금 너무 밋밋하다.
- [x] repo tag들 추가 
- [x] readme 추가
- [x] 이용하지 않는 frontmatter 삭제 
- [x] example 용 마크다운 파일 수정. (수식, 사진도 같이 보이도록)
- [x] package.json 수정
- [x] src/styles/responsive <-- case 수정
